# Generated by Django 2.1.5 on 2019-01-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBSourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=100, verbose_name='数据库类型名')),
                ('describe', models.TextField(verbose_name='数据库类型描述')),
                ('host', models.CharField(max_length=100, verbose_name='数据库地址')),
                ('port', models.IntegerField(verbose_name='数据库端口')),
                ('database', models.CharField(max_length=200, verbose_name='数据库')),
                ('user', models.CharField(max_length=10, verbose_name='数据库用户名')),
                ('password', models.CharField(max_length=24, verbose_name='数据库密码')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'db_source',
            },
        ),
    ]
