# Generated by Django 2.1.5 on 2019-01-18 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uuid', models.CharField(max_length=50, verbose_name='文件id')),
                ('file_path', models.TextField(verbose_name='文件路径')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'email_file',
            },
        ),
        migrations.CreateModel(
            name='TaskEmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(max_length=50, verbose_name='执行任务的唯一id')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'task_email',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名')),
                ('describe', models.TextField(verbose_name='任务描述')),
                ('code_context', models.TextField(verbose_name='代码内容')),
                ('task_status', models.BooleanField(default=True, verbose_name='任务状态')),
                ('insert_time', models.DateTimeField(auto_now=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('db_source', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='db_source', to='user.DBSourceModel', verbose_name='源数据库')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.AddField(
            model_name='taskemailmodel',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.TaskModel', verbose_name='task 外键'),
        ),
        migrations.AddField(
            model_name='taskemailmodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='执行用户'),
        ),
        migrations.AddField(
            model_name='emailfile',
            name='task_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task_email', to='task.TaskEmailModel', verbose_name='TaskEmailModel 外键'),
        ),
    ]
