FROM centos:7

# 安装一些包
RUN yum install -y wget

# 更新yum
RUN wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
yum clean all && \
yum makecache
RUN yum update -y
RUN yum install -y gcc bzip2

# 下载python
RUN wget --quiet https://repo.continuum.io/archive/Anaconda3-2018.12-Linux-x86_64.sh  -O ~/anaconda.sh && \
/bin/bash ~/anaconda.sh -b -p /opt/conda && \
rm ~/anaconda.sh && \
echo "export PATH=/opt/conda/bin:$PATH" >> ~/.bashrc